### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by jrappen** [tolking/vuepress-theme-default-prefers-color-scheme#30]
Workflow replacements as discussed in #28.

---

### `deploy`

```yaml
name: deploy

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      # Compare https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build docs
        run: |
          yarn install
          vuepress build docs/ --no-cache

      # Compare https://github.com/peaceiris/actions-gh-pages
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'deploy:'
```

### `test`

```yaml
name: test

on:
  push:
    branches:
      - dev
      - next
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - master
      - dev
      - next
    paths:
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:

      # Compare https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: '[Test] Build docs'
        run: |
          yarn install
          vuepress build docs/ --no-cache

      # don't deploy
```
